# Generated by Django 2.1.5 on 2019-02-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvocadoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avocadoType', models.CharField(max_length=200)),
                ('avocadoPrice', models.CharField(max_length=200)),
            ],
        ),
    ]
